spawn dune exec ./note_trainer.exe -- --seed 1

expect "note_trainer using seed 1"

expect "Note G transposed up 5 semi-tones gives what? \r"
send "C\r"
expect "Correct!\r"

expect "Note E transposed up 3 semi-tones gives what? \r"
send "X\r"
expect "Correct!\r"

expect "Note F transposed down 3 semi-tones gives what? \r"
send "X\r"
expect "Incorrect!\r"
expect "Note F transposed down 3 semi-tones gives what? \r"
send "G\r"
expect "Correct!\r"

send "\004"

interact
